from __future__ import annotations

# TODO: normalize money strings with a parse_money() helper.

_ITEM_LIST = [
    {
        "name": "Copper Wire",
        "unlock_cost_cash": "Free",
        "sell_price": "10K",
        "inputs": {"Copper Bar": 5},
        "craft_time_s": 60,
        "used_for": ["Battery (2)", "Circuit (10)", "Rover (10)"],
    },
    {
        "name": "Iron Nails",
        "unlock_cost_cash": "20K",
        "sell_price": "20K",
        "inputs": {"Iron Bar": 5},
        "craft_time_s": 120,
        "used_for": [
            "Hammer (2)",
            "Telescope 3 (10)",
            "Colonization Scouting (15)",
            "Preferred Vendor (200)",
        ],
    },
    {
        "name": "Battery",
        "unlock_cost_cash": "50K",
        "sell_price": "70K",
        "inputs": {"Copper Wire": 2, "Copper Bar": 10},
        "craft_time_s": 240,
        "used_for": [
            "Advanced Battery (30)",
            "Resource Details (3)",
            "Ore Targeting (50)",
            "Rover Advanced Logistics (20)",
            "Advanced Mining (5)",
        ],
    },
    {
        "name": "Hammer",
        "unlock_cost_cash": "100K",
        "sell_price": "135K",
        "inputs": {"Iron Nails": 2, "Lead Bar": 5},
        "craft_time_s": 480,
        "used_for": [
            "Motor (200)",
            "Telescope 4 (5)",
            "Market Insight (10)",
            "Ore Targeting (100)",
            "Colonization Efficiency (10)",
            "Colony Renegotiation (400)",
            "Advanced Cargo Handling (5)",
            "Preferred Vendor (75)",
        ],
    },
    {
        "name": "Glass",
        "unlock_cost_cash": "200K",
        "sell_price": "220K",
        "inputs": {"Silicon Bar": 10},
        "craft_time_s": 720,
        "used_for": [
            "Lens (1)",
            "Solar Panel (10)",
            "Thermal Scanner (5)",
            "Advanced Thrusters (2)",
            "Advanced Furnace (3)",
        ],
    },
    {
        "name": "Circuit",
        "unlock_cost_cash": "400K",
        "sell_price": "620K",
        "inputs": {"Silicon Bar": 5, "Aluminum Bar": 5, "Copper Wire": 10},
        "craft_time_s": 1200,
        "used_for": [
            "Basic Computer (5)",
            "Solar Panel (5)",
            "Asteroid Harvester (5)",
            "Cargo Logistics (3)",
            "Telescope 5 (3)",
            "Contract Manager (20)",
            "Advanced Alloy Value (3)",
            "Preferred Vendor (40)",
        ],
    },
    {
        "name": "Lens",
        "unlock_cost_cash": "1M",
        "sell_price": "1.1M",
        "inputs": {"Glass": 1, "Silver Bar": 5},
        "craft_time_s": 2400,
        "used_for": [
            "Laser (1)",
            "Laser Torch (5)",
            "Telescope (20)",
            "Inside Trader (10)",
            "Alchemy (6)",
            "Rover Advanced Logistics (10)",
            "Advanced Crafter (5)",
            "Advanced Item Value (1)",
        ],
    },
    {
        "name": "Laser",
        "unlock_cost_cash": "2M",
        "sell_price": "3.2M",
        "inputs": {"Gold Bar": 5, "Lens": 1, "Iron Bar": 10},
        "craft_time_s": 3600,
        "used_for": [
            "Laser Torch (2)",
            "Thermal Scanner (2)",
            "Telescope 6 (3)",
            "Colonization Advanced Efficiency (10)",
            "Superior Alloy Value (30)",
        ],
    },
    {
        "name": "Basic Computer",
        "unlock_cost_cash": "5M",
        "sell_price": "7.60M",
        "inputs": {"Circuit": 5, "Silver Bar": 5},
        "craft_time_s": 4800,
        "used_for": [
            "Advanced Computer (5)",
            "Market Manipulation (10)",
            "Advanced Ore Targeting (100)",
            "Advanced Alchemy (6)",
            "Rover Scanning Module (1)",
            "Advanced Rover Resupply (1)",
            "Contract Manager (20)",
            "Smelting Specialist (5)",
        ],
    },
    {
        "name": "Solar Panel",
        "unlock_cost_cash": "10M",
        "sell_price": "12.5M",
        "inputs": {"Circuit": 5, "Glass": 10},
        "craft_time_s": 6000,
        "used_for": [
            "Space Probe (20)",
            "Asteroid Auto Miner (100)",
            "Rover Resupply (1)",
            "Telescope 7 (3)",
            "Crafting Efficiency (40)",
        ],
    },
    {
        "name": "Laser Torch",
        "unlock_cost_cash": "20M",
        "sell_price": "31M",
        "inputs": {"Bronze Bar": 5, "Laser": 2, "Lens": 5},
        "craft_time_s": 7200,
        "used_for": [
            "Navigation Module (2)",
            "Plasma Torch (5)",
            "Rover Resupply (1)",
            "Manager Training (1)",
            "Telescope 8 (3)",
            "Colonization Superior Efficiency (15)",
            "Superior Mining (10)",
            "Superior Crafting (20)",
            "Superior Item Value (25)",
        ],
    },
    {
        "name": "Advanced Battery",
        "unlock_cost_cash": "30M",
        "sell_price": "35M",
        "inputs": {"Steel Bar": 20, "Battery": 30},
        "craft_time_s": 9000,
        "used_for": [
            "Accumulator (3)",
            "Telescope 9 (3)",
            "Advanced Manager Training (10)",
            "Superior Thrusters (4)",
            "Superior Crafting (10)",
            "Crafting Specialist (2)",
            "Smelting Specialist (2)",
        ],
    },
    {
        "name": "Thermal Scanner",
        "unlock_cost_cash": "50M",
        "sell_price": "71.5M",
        "inputs": {"Platinum Bar": 5, "Laser": 2, "Glass": 5},
        "craft_time_s": 10800,
        "used_for": [
            "Navigation Module (1)",
            "Asteroid Scanner (30)",
            "Advanced Ore Targeting (15)",
            "Telescope 10 (3)",
            "Advanced Contract Manager (10)",
            "Terraforming (10)",
            "Superior Crafting (2)",
            "Advanced Furnace Overdrive (10)",
        ],
    },
    {
        "name": "Advanced Computer",
        "unlock_cost_cash": "120M",
        "sell_price": "180M",
        "inputs": {"Titanium Bar": 5, "Basic Computer": 5},
        "craft_time_s": 12600,
        "used_for": [
            "Telescope (1)",
            "Gravity Chamber (60)",
            "Asteroid Auto Miner (20)",
            "Advanced Market Manipulation (10)",
            "Superior Alchemy (5)",
            "Advanced Manager Training (2)",
            "Advanced Contract Manager (10)",
            "Telescope 11 (3)",
            "Crafting Specialist (2)",
        ],
    },
    {
        "name": "Navigation Module",
        "unlock_cost_cash": "250M",
        "sell_price": "1B",
        "inputs": {"Thermal Scanner": 1, "Laser Torch": 2},
        "craft_time_s": 13500,
        "used_for": ["Teleporter (250)", "Asteroid Scanner (5)", "Leader (5)", "Telescope 12 (3)"],
    },
    {
        "name": "Plasma Torch",
        "unlock_cost_cash": "550M",
        "sell_price": "1.15B",
        "inputs": {"Iridium Bar": 15, "Laser Torch": 5},
        "craft_time_s": 15000,
        "used_for": [
            "Nuclear Capsule (1)",
            "Advanced Asteroid Harvester (50)",
            "Furnace Overdrive (1)",
        ],
    },
    {
        "name": "Radio Tower",
        "unlock_cost_cash": "1.50B",
        "sell_price": "1.45B",
        "inputs": {"Platinum Bar": 75, "Aluminum Bar": 150, "Titanium Bar": 50},
        "craft_time_s": 15600,
        "used_for": ["Telescope 13 (3)"],
    },
    {
        "name": "Telescope",
        "unlock_cost_cash": "5B",
        "sell_price": "2.7B",
        "inputs": {"Lens": 20, "Advanced Computer": 1},
        "craft_time_s": 16800,
        "used_for": [
            "Space Probe (1)",
            "Advanced Asteroid Scanner (150)",
            "Advanced Market Manipulation (5)",
            "Advanced Leader (10)",
        ],
    },
    {
        "name": "Satellite Dish",
        "unlock_cost_cash": "17.50B",
        "sell_price": "3.4B",
        "inputs": {"Steel Bar": 150, "Palladium Bar": 30},
        "craft_time_s": 18000,
        "used_for": ["Space Probe (1)", "Telescope 14 (3)", "Advanced Terraforming (10)"],
    },
    {
        "name": "Motor",
        "unlock_cost_cash": "60B",
        "sell_price": "7B",
        "inputs": {"Bronze Bar": 500, "Hammer": 200},
        "craft_time_s": 19200,
        "used_for": [
            "Wind Turbine (1)",
            "Market Accelerator (1)",
            "Advanced Leader (10)",
            "Telescope 15 (5)",
            "Furnace Overdrive Efficiency (1)",
        ],
    },
    {
        "name": "Accumulator",
        "unlock_cost_cash": "100B",
        "sell_price": "12B",
        "inputs": {"Osmium Bar": 20, "Advanced Battery": 3},
        "craft_time_s": 20400,
        "used_for": ["Robot (90)", "Telescope 16 (3)"],
    },
    {
        "name": "Nuclear Capsule",
        "unlock_cost_cash": "200B",
        "sell_price": "26B",
        "inputs": {"Rhodium Bar": 5, "Plasma Torch": 1},
        "craft_time_s": 21000,
        "used_for": ["Nuclear Reactor (1)", "Fusion Capsule (100)", "Telescope 17 (3)"],
    },
    {
        "name": "Wind Turbine",
        "unlock_cost_cash": "500B",
        "sell_price": "140B",
        "inputs": {"Aluminum Bar": 300, "Motor": 1},
        "craft_time_s": 21600,
        "used_for": ["Telescope 18 (3)"],
    },
    {
        "name": "Space Probe",
        "unlock_cost_cash": "1T",
        "sell_price": "180B",
        "inputs": {"Satellite Dish": 1, "Telescope": 1, "Solar Panel": 25},
        "craft_time_s": 22200,
        "used_for": ["Subspace Relay (28)", "Advanced Asteroid Harvester (1)"],
    },
    {
        "name": "Nuclear Reactor",
        "unlock_cost_cash": "2T",
        "sell_price": "1T",
        "inputs": {"Nuclear Capsule": 1, "Iridium Bar": 300},
        "craft_time_s": 22800,
        "used_for": [
            "Gravity Chamber (1)",
            "Fusion Reactor (50)",
            "Superior Asteroid Harvester (10)",
            "Telescope 19 (4)",
        ],
    },
    {
        "name": "Collider",
        "unlock_cost_cash": "3T",
        "sell_price": "2T",
        "inputs": {"Inerton Alloy": 500, "Quadium Alloy": 100},
        "craft_time_s": 23100,
        "used_for": ["Fusion Reactor (40)", "Debris Scanner (1)", "Telescope 20 (5)"],
    },
    {
        "name": "Gravity Chamber",
        "unlock_cost_cash": "6T",
        "sell_price": "15T",
        "inputs": {"Advanced Computer": 60, "Nuclear Reactor": 1},
        "craft_time_s": 24300,
        "used_for": [
            "Teleporter (1)",
            "Debris Scanner (8)",
            "Advanced Market Accelerator (1)",
            "Telescope 21 (5)",
        ],
    },
    {
        "name": "Robot",
        "unlock_cost_cash": "15T",
        "sell_price": "50T",
        "inputs": {"Scrith Alloy": 300, "Accumulator": 90},
        "craft_time_s": 26000,
        "used_for": ["Telescope 22 (6)", "Advanced Robot (100)"],
    },
    {
        "name": "Fusion Capsule",
        "unlock_cost_cash": "75T",
        "sell_price": "240T",
        "inputs": {"Uru Alloy": 200, "Vibranium Alloy": 100, "Nuclear Capsule": 100},
        "craft_time_s": 27000,
        "used_for": ["Fusion Reactor (1)"],
    },
    {
        "name": "Teleporter",
        "unlock_cost_cash": "500T",
        "sell_price": "1.8q",
        "inputs": {"Navigation Module": 250, "Gravity Chamber": 1},
        "craft_time_s": 29000,
        "used_for": ["Subspace Relay (1)", "Advanced Teleporter (100)"],
    },
    {
        "name": "Fusion Reactor",
        "unlock_cost_cash": "2.5q",
        "sell_price": "40q",
        "inputs": {"Fusion Capsule": 1, "Collider": 40, "Nuclear Reactor": 50},
        "craft_time_s": 31000,
        "used_for": ["Advanced Robot (4)"],
    },
    {
        "name": "Subspace Relay",
        "unlock_cost_cash": "15q",
        "sell_price": "1Q",
        "inputs": {"Space Probe": 70, "Satellite Dish": 100, "Teleporter": 1},
        "craft_time_s": 32300,
        "used_for": ["Advanced Teleporter (4)"],
    },
    {
        "name": "Advanced Robot",
        "unlock_cost_cash": "142.00q",
        "sell_price": "29.5Q",
        "inputs": {"Robot": 100, "Fusion Reactor": 5},
        "craft_time_s": 62300,
        "used_for": ["Quantum CPU (5)"],
    },
    {
        "name": "Advanced Teleporter",
        "unlock_cost_cash": "1.49Q",
        "sell_price": "650Q",
        "inputs": {"Subspace Relay": 5, "Teleporter": 100, "Xynium Alloy": 1000},
        "craft_time_s": 115200,
        "used_for": ["Deflector Shield (5)"],
    },
    {
        "name": "Quantum CPU",
        "unlock_cost_cash": "20.00Q",
        "sell_price": "14s",
        "inputs": {"Advanced Robot": 4, "Quolium Alloy": 500},
        "craft_time_s": 120000,
        "used_for": [],
    },
    {
        "name": "Deflector Shield",
        "unlock_cost_cash": "270.00Q",
        "sell_price": "320s",
        "inputs": {"Advanced Teleporter": 4, "Luterium Alloy": 400},
        "craft_time_s": 125000,
        "used_for": [],
    },
    {
        "name": "Warp Core",
        "unlock_cost_cash": "3.65s",
        "sell_price": "6.80 S",
        "inputs": {"Wind Turbine": 160, "Fusion Reactor": 40, "Quantum CPU": 4},
        "craft_time_s": 180000,
        "used_for": ["(50h)"],
    },
    {
        "name": "Deep Space Scanner",
        "unlock_cost_cash": "49.30s",
        "sell_price": "145 S",
        "inputs": {"Advanced Battery": 250, "Aqualite Alloy": 1000, "Deflector Shield": 4},
        "craft_time_s": 188000,
        "used_for": [],
    },
    {
        "name": "AntiMatter Cell",
        "unlock_cost_cash": "665.00s",
        "sell_price": "3.2 O",
        "inputs": {"Nuclear Reactor": 50, "Palladium Bar": 10000, "Warp Core": 4},
        "craft_time_s": 194000,
        "used_for": [],
    },
]

ITEMS = {i["name"]: i for i in _ITEM_LIST}


def get_item(name: str):
    return ITEMS.get(name)


def list_items() -> list[str]:
    return [i["name"] for i in _ITEM_LIST]
